[build]
  publish = "build"
  command = "bash build.sh"  # Use "build.bat" for Windows

[build.environment]
  GIT_LFS_ENABLED = "true"
  GIT_SUBMODULE_STRATEGY = "recursive"

[[redirects]]
  from = "/"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200