[build]
  # Since your files are already in the root directory, not in a "dist" folder
  publish = "."
  # If you don't have a build command, you can remove this line or set it to an empty string
  command = ""

[[redirects]]
  from = "/"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200